import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Paper } from '@mui/material'
import { Header } from '../components/Header/Header';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Test Proj</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
    </div>
  )
}
